spring.application.name=com.Ecom
spring.datasource.url=jdbc:postgresql://localhost:5432/myecom_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.security.user.name=oreo
spring.security.user.password=1234

